### ISSUE TITLE
Examples not working on Smartphone : ( Iphone 11 Pro - iOS 14.0.1 - Safari )

### ISSUE THREAD

**Issue by satolas** [Rufus31415/Simple-WebXR-Unity#13]
I open this for example : https://rufus31415.github.io/webxr/PaintExample/
From the mobile. Unity WebGL project completely loads and stays black, nothing happens.
I tried other examples as well, same result.

**Comment by satolas** [comment]
I found out a solution so the scene is launching at least :
On iOS, go to Settings/Safari/Advanced/Experimental Features. And if WebGL 0.2 is enabled, disable it.

![AFC67AF0-09C2-44E3-BD3E-1B2A0DA3FE63](https://user-images.githubusercontent.com/29286385/96024924-be703b00-0e54-11eb-850e-ce24e08e345c.jpeg)

**Comment by satolas** [comment]
But... now I have a new issue ^^
![Uploading ADACC315-B850-4F33-AF26-3EC59FDBEF5C.jpeg…]()

**Comment by Rufus31415** [comment]
Indeed, I have just tested. WebGL 2.0 is not fully supported in WebKit. 
As for WebXR, Safari does not support it yet. The only browser on iOS that supports it is XRViewer : https://apps.apple.com/fr/app/webxr-viewer/id1295998056
Thanks for your remark. I will add this info on the example page.

**Comment by Prakash19921206** [comment]
@Rufus31415 sorry to comment on closed issue.
Just wanted to know if there's an work around for ios
currently i'm in iPhone 14 pro (ios 17.3.1)
i don't see WebGl 2.0 anywhere in Settings/Safari/Advanced/Experimental Features 


i noticed few toggles at settings -> safari ->Advanced ->Feature Flags [please check images attached]
tried switching webgl related toggles but none of them helped.
![IMG_1095](https://github.com/Rufus31415/Simple-WebXR-Unity/assets/128677741/1d8be965-8578-4840-b835-4d00591e9c76)


i understand that it doesn't enter into AR (camera) on safari, but its not working on Mozilla WebXR Viewer  as well.
i see "Enter AR" button, upon clicking in WebXR browser i see an error as attached in screenshot below
![IMG_1097](https://github.com/Rufus31415/Simple-WebXR-Unity/assets/128677741/08ee9f85-b125-44cb-9145-0f663f344843)
![IMG_1098](https://github.com/Rufus31415/Simple-WebXR-Unity/assets/128677741/d7159d32-84a6-448e-902f-eae7b8eca32c)

Any advice would be greatly appreciated!
Thanks & Regards
Prakash

**Comment by Rufus31415** [comment]
It seems that after updating iOS, a number of functions no longer work in the XRViewer browser, even some basic examples no longer work. I'll dig into it when I have a moment.

**Comment by Rufus31415** [comment]
This demo doesn't use the WebXR JavaScript API.
It uses raw image access and image processing to render the 3D model point of view

**Comment by ThirdEyeDev** [comment]
i see, Thank for letting me know.
so its using some javascript based library for 3d tracking?

interestingly it supports urp too but i felt quality isn't that good at the moment
https://webar.imaginerealities.com.au/wt/tikbalang/

**Comment by Prakash19921206** [comment]
Thanks for letting me know.
when you mentioned image processing, it is using some javascript based library for 6dof tracking?

sorry, accidentally posted from different account.
for anybody who is interested i was talking about following url
https://webar.imaginerealities.com.au/wt/demo

interestingly it supports urp too but i felt quality isn't that good at the moment
https://webar.imaginerealities.com.au/wt/tikbalang/

**Comment by Rufus31415** [comment]
The lib behind this is this one : https://assetstore.unity.com/packages/tools/camera/imagine-webar-image-tracker-240128
