### ISSUE TITLE
Properly handle end of session

### ISSUE THREAD

**Issue by Rufus31415** [Rufus31415/Simple-WebXR-Unity#14]
When a session ends, the WebGL app should return to a 2D usable state. Now, the canvas is black

**Comment by b29b** [comment]
unity scene freezes on end of session on android, i tried reloading scene after xr session ends, doesnt seem to work...
unity 2019.4

**Comment by Rufus31415** [comment]
I know, all cameras are deleted, it should not

**Comment by Rufus31415** [comment]
Corrected in last commit https://github.com/Rufus31415/Simple-WebXR-Unity/commit/e60b96d69689a0025deba7163d2ea2467b3848da
