### ISSUE TITLE
Vibration feedback?

### ISSUE THREAD

**Issue by TheBricktop** [Rufus31415/Simple-WebXR-Unity#23]
Is there a way to trigger vibration feedback on the controllers?

**Comment by Rufus31415** [comment]
That's a good point, I'll add that.
WebXR supports it and it's not complicated to add: https://w3c.github.io/gamepad/extensions.html#gamepadhapticactuator-interface
It seems to me that Quest is compatible

**Comment by TheBricktop** [comment]
Good to hear!
