### ISSUE TITLE
camera always starts at vector3 zero, even if parented and moved to custom position

### ISSUE THREAD

**Issue by HawkenKing** [Rufus31415/Simple-WebXR-Unity#24]
I'm having trouble starting the camera / rig at a designated position. If I move it to X-3 for example, it always starts at X 0.

Tested on Oculus Quest Browser

**Comment by Rufus31415** [comment]
Thank you for all your remarks.
By design, the camera always starts at Vector3.Zero. I'm thinking of adding OffsetPosition and OffsetRotation properties that will add this amount to the position, to make teleport or initial offset, would that suit you ?

**Comment by HawkenKing** [comment]
Allowing the camera to be parented by a rig is the usual setup in VR, if this needs additional variables to work it adds complexity to the usual manner of going about things.

**Comment by Rufus31415** [comment]
Second camera as now same parent as main camera and its local position is changed by SimpleWebXR
