### ISSUE TITLE
MSAA support

### ISSUE THREAD

**Issue by HawkenKing** [Rufus31415/Simple-WebXR-Unity#25]
would be nice to get anti-aliasing working without the framerate hit. For example 4x MSAA

Tested on Oculus Quest Browser

**Comment by Rufus31415** [comment]
Yes, on Quest the rendering is really bad. I've never tried MSAA. I'm surprised that the rendering is clean on all other platforms...
In my example scenes, I could enable MSAA on each Camera in Project Setting / Graphics.
