### ISSUE TITLE
Camera start position should always be 0

### ISSUE THREAD

**Issue by Rufus31415** [Rufus31415/Simple-WebXR-Unity#27]
On Quest, start position is not zero contrary to other browsers.
For MRTK : move playspace to camera.main.transform.position at startup

**Comment by ThePaperDragon** [comment]
On the Quest browser, 0 is floor level.  I would like all browsers to function like this, otherwise it is hard to determine floor level.

**Comment by Rufus31415** [comment]
@ThePaperDragon  Unfortunately not all browsers are aware of the floor, that's why I added SimpleWebXR.UserHeight which is different from 0 if the browser supports floor space.
It was therefore chosen to always start at the local position 0
