### ISSUE TITLE
Painter not working on Smartphone (Android)

### ISSUE THREAD

**Issue by Tunkali** [Rufus31415/Simple-WebXR-Unity#31]
Hey there,

I was looking for an webxr exporter for my projects (mainly AR on phones) and on testing the examples I saw that the painter is not working on my device (Samsung S8) in any of the browsers. Camera has passthrough but there is not paint working.

**Comment by Rufus31415** [comment]
Paint example is not the most suitable for smartphone, but it works with Chrome on my Pixel 5. You just have to press on the screen and move back, like on this video: https://youtu.be/cUkAdI4lJOA?t=85

Do the other demos work on your phone?  https://rufus31415.github.io/webxr/MRTK-HandInteraction/
