### ISSUE TITLE
Web-AR with Image Tracking

### ISSUE THREAD

**Issue by Jorg313** [Rufus31415/Simple-WebXR-Unity#40]
Is it possible to create one and if are there examples? Is it posible to make it work on android?

**Comment by Rufus31415** [comment]
Marker tracking is a feature that will exist in WebXR soon. As soon as it is stable, I will implement it in SimpleWebXR.

In the meantime, you can find the progress of the specification here:
- https://immersive-web.github.io/marker-tracking/
- https://github.com/immersive-web/marker-tracking
