### ISSUE TITLE
MRTK 2.7.3 Support

### ISSUE THREAD

**Issue by pajama** [Rufus31415/Simple-WebXR-Unity#50]
Do you know of any blockers for supporting 2.7.3? I can take a stab at it, but would love some guidance if it's already been attempted. Thanks!

**Comment by Rufus31415** [comment]
I think SimpleWebXR is compatible with the new versions of MRTK. Just replace the dependencies here and let Unity update the packages:

https://github.com/Rufus31415/Simple-WebXR-Unity/blob/a9060413037d6b5dd985abba29ed17fcd51ff79d/SimpleWebXR-Demo/Packages/manifest.json#L13

**Comment by pajama** [comment]
Seems to be working well!
