### ISSUE TITLE
In oculus browser not detect VR mode only AR Mode

### ISSUE THREAD

**Issue by BussinessInnovation** [Rufus31415/Simple-WebXR-Unity#56]
In oculus browser not detect VR mode, only detect AR Mode. 

How can I force the VR mode on the Oculus Quest and keep the AR mode enabled on the smartphone?

thx!

**Comment by Rufus31415** [comment]
As mentioned here, AR takes priority over VR.
As Oculus now supports both, AR is chosen.

https://github.com/Rufus31415/Simple-WebXR-Unity/blob/492fa0893c2b41a7a39207cbc96a76707fa823c6/com.rufus31415.simplewebxr/Runtime/Plugins/WebGL/SimpleWebXR.jslib#L574

**Comment by chismer** [comment]
Ok. Thanks! 
How could I force VR to be activated in the case of Oculus? From unity could?

**Comment by Rufus31415** [comment]
I suggest you replace the line with the following to force immersive-vr :

```js
    navigator.xr.requestSession('immersive-vr', { optionalFeatures: ['local-floor', 'hand-tracking'] }).then(function (session) {
```

**Comment by chismer** [comment]
Thank you! I have already changed it. I've saved, restarted Unity, compiled and it's still detecting AR. Do I have to do something to compile the jslib?

**Comment by chismer** [comment]
unfortunately it still detects AR.

**Comment by AdrianBotana** [comment]
I just tested this solution and it worked for me. Thanks!
