### ISSUE TITLE
Suspicius rediriection/warning from browser when clicked on the link in "samples"

### ISSUE THREAD

**Issue by rakshithvenepally** [Rufus31415/Simple-WebXR-Unity#58]
The link from samples is being redirected to another page, which is throwing up a warning in the browser. 
![grafik](https://github.com/Rufus31415/Simple-WebXR-Unity/assets/56837228/bbefa54d-a0c2-44d7-8df0-0d37075ace0a)

The original [link](https://github.com/Rufus31415/rufus31415.github.io/tree/master/webxr) however does show the samples page

not sure if this is expected?

**Comment by Rufus31415** [comment]
Where exactly is this suspicious link ?

**Comment by rakshithvenepally** [comment]
https://github.com/Rufus31415/Simple-WebXR-Unity?tab=readme-ov-file#samples

**Comment by Rufus31415** [comment]
OK thanks.
I used to use downgit to download a whole directory, but this service doesn't seem to work anymore. I've just updated the link to the website repo directly.

**Comment by rakshithvenepally** [comment]
Thank you for the quick response and still maintaining it, your work is incredibly helpful to me at the moment!

**Comment by Rufus31415** [comment]
👍  Don't hesitate to share your work with me :)
